### ISSUE TITLE
Questions about slip distribution results

### ISSUE THREAD

**Issue by emiliaxin** [hvasbath/beat#93]
Hi,
I have followed the steps in Example 4 to obtain the fault slip distribution in my study area. However, how can I get information from the results about the average slip angle and average slip of the fault, the location, and the depth of the epicenter?

**Here are my results.**
[scenes_-1_max_latlon_1.pdf](https://github.com/hvasbath/beat/files/7749132/scenes_-1_max_latlon_1.pdf)
[scenes_-1_max_local_1.pdf](https://github.com/hvasbath/beat/files/7749134/scenes_-1_max_local_1.pdf)
[slip_dist_43_max_1.pdf](https://github.com/hvasbath/beat/files/7749137/slip_dist_43_max_1.pdf)
[summary.txt](https://github.com/hvasbath/beat/files/7749138/summary.txt)

Could you give me some suggestions?
Thank you

**Comment by hvasbath** [comment]
Hi @emiliaxin ,

you obtained some nice results there. I have to admit I cannot completely follow why you would be interested in these average values? Then I would suggest you take the results from the geometry estimation, where the rake- angle is the slip-angle you are asking for. Regarding epicenter, how do you define epicenter when you have only static data available? You could talk about the location and depth of the region with maximum slip. The geometry parameters of your reference fault, such as location and angless are in the results of your geometry estimation-or if you skipped that in the attributes of your reference_faults defined in the geodetic_config.gf_config.

I still have some comments on your results:
- please reduce the number of patches by increasing the patch size- you have now 1k unknowns for few hundred of observations. Which is why you hit the bound with your laplacian at -2 ..., now you used 1km patch size, please use at least 2km
- do you plan to include seismic data as well? If not, you could also do data dependend patch size estimation based on Atzori & Antonioli 2011. This comes up so often recently- I will work on a tutorial on how to do this- this evening .... will keep you posted.
- if you specify in your misfit plots the --nensemble=200 parameter you get a histogram of Variance Reduction for each dataset.(of course you could also set it to any other value you prefer)
- please also make the stage_posterior plot and check if you hit the bounds with any other parameters ,,,

**Comment by emiliaxin** [comment]
@hvasbath I greatly appreciate your answers and suggestions.

**Comment by hvasbath** [comment]
Dear @emiliaxin I am sorry for the late response, but it took much longer than expected to finish the tutorial. I also found I needed to implement much more to make it useful for the general user. But that greatly improved everything and I think its now very useable. Your feedback on unclear things in the text/potential bugs etc is greatly appreciated!

https://pyrocko.org/beat/docs/current/examples/FFI_static_resolution.html

P.S.: Please make sure to update to the latest released version ;)

**Comment by emiliaxin** [comment]
Dear @hvasbath 
Thank you for updating such an excellent tutorial.
I am so sorry to bother you again with another question.  I am now trying to perform a RectangularSource inversion for my own data. I would like to know how to quickly determine the parameter range (lower, upper and testvalue values) of the Rectangular Source in the "Optimization setup" based on apriori knowledge. Is there a good way to do this?

**Here is my configuration file.**
[config_geometry.txt](https://github.com/hvasbath/beat/files/7911153/config_geometry.txt)


I look forward to your reply, thank you very much.

**Comment by hvasbath** [comment]
First of all I strongly urge you to rename the Laquila stuff in your config to the name of the new earthquake, this gets messy very fast!
If there are already studies for your earthquake published you could look into their best fit parameters as an orientation.
Then I see you have SAR data you would read your interferograms and usually you can get a good grasp about position, strike and dip angles, as well as fault length. You can also look at the moment tensor solution from the EQ catalog.
Then of course you need to also have a look at the tectonics and geology in the region. All these factors give you usually a good grasp of what might be going on.

Then of course these prior bounds should not be too tight, as you want to allow to also discover new things, that are not possible to discover with the classical methods, which is the true power of the non-linear Bayesian approach. So usually I tend to leave my prior bounds very wide, but they need to be physically sensible.
Often you find that one or the other parameter bound was poorly set in the first run for example your sampler hits the prior bound and you will have to adjust them and rerun anyways several times.

Finally, you can run some fast forward models for example using a simple Okada Source and try to understand why which EQ mechanism produces which deformation pattern. That is an exercise we do with students during seminars ...
You can use the talpa tool for that-also developed by team pyrocko:
https://pyrocko.org/kite/docs/current/tools/talpa.html

You should discuss these things also with your supervisor, as this is not software-related but rather a general question of how to approach source studies, which is now too little space and tedious to cover in such a github- issue ;) .

**Comment by emiliaxin** [comment]
Thank you very much for your reply.
