### ISSUE TITLE
Questions about the summary

### ISSUE THREAD

**Issue by emiliaxin** [hvasbath/beat#97]
Dear @hvasbath，
 I got the "summary.txt" for my case. And I would like to know why dip>90° in the result?
Also, does "hpd_0.5, hpd_99.5" mean to get 99% confidence interval for each parameter?

**Here are my summary.txt.**
[summary.txt](https://github.com/hvasbath/beat/files/8110061/summary.txt)

Could you please give me some suggestions?
Thank you very much!

**Comment by emiliaxin** [comment]
Thank you very much for your patient response.
I set Dip between 0 and 90 degrees at the beginning, but got bad results as shown in the figure below.
[summary.txt](https://github.com/hvasbath/beat/files/8113762/summary.txt)

![corr_hist_30_max_0](https://user-images.githubusercontent.com/91539014/155066573-79b58828-c712-41b7-8450-312cf00df468.png)

**Comment by hvasbath** [comment]
Yes! Perfect, so thats also why this functionality exists ;) . Sometimes its not so clear whether a faults dips one or the other side and in the setup one needs that possibility to sample both sides. Of course, a strike of 289 and a dip of 82 would be able to resolve the same fault configuration, but due to the large jump in strikes its harder to sample. Which is why I went for that other possibility with dips above 90degree.

**Comment by emiliaxin** [comment]
Thank you!
